---
- name: Un playbook muy muy sencillo
  hosts: web
  become: yes
  tasks:
    - name: Ensure SSH MaxStartups is configured
      block:
      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*MaxStartups\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes
      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*MaxStartups\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1
      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*MaxStartups\s+
          line: MaxStartups 10:30:60
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      tags:
      - CCE-90718-8

    - name: Ensure cyrus-imapd is removed
      package:
        name: cyrus-imapd
        state: absent
      tags:
      - CCE-88119-3
      
    - name: Ensure nginx is removed
      package:
        name: nginx
        state: absent
      tags:
      - CCE-88034-4

    - name: Enable SSH Warning Banner
      block:
      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*Banner\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes
      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*Banner\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1
      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*Banner\s+
          line: Banner /etc/issue.net
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      tags:
      - CCE-87978-3 

    - name: Remove /etc/at.deny
      file:
        path: /etc/at.deny
        state: absent
      tags:
      - CCE-86945-3 
       
    - name: Remove /etc/cron.deny
      file:
        path: /etc/cron.deny
        state: absent
      tags:
      - CCE-86849-7
 

     # Dada la cantidad de información sentsible en un core dump,
    # al contener una imagen de toda la memoria,
    # es un riesgo que pueda ser obtenida por un agente externo
    - name: Disable core dump backtraces
      block:
      - name: Check for duplicate values
        lineinfile:
          path: /etc/systemd/coredump.conf
          create: false
          regexp: ^\s*ProcessSizeMax\s*=\s*
          state: absent
        check_mode: true
        changed_when: false
        register: dupes
      - name: Deduplicate values from /etc/systemd/coredump.conf
        lineinfile:
          path: /etc/systemd/coredump.conf
          create: false
          regexp: ^\s*ProcessSizeMax\s*=\s*
          state: absent
        when: dupes.found is defined and dupes.found > 1
      - name: Insert correct line to /etc/systemd/coredump.conf
        lineinfile:
          path: /etc/systemd/coredump.conf
          create: false
          regexp: ^\s*ProcessSizeMax\s*=\s*
          line: ProcessSizeMax=0
          state: present
 
    - name: Prevent user modification of GNOME3 disablement of Login User List
      # This module ensures a particular line is in a file,
      ansible.builtin.lineinfile:
        # The file to modify.
        path: /etc/dconf/db/gdm.d/locks/00-security-settings-lock
        # The regular expression to look for in every line of the file.
        regexp: ^/org/gnome/login-screen/disable-user-list$
        line: /org/gnome/login-screen/disable-user-list
        # If specified, the file will be created if it does not already exist.
        create: true


    - name: Enable PAM
      block:
      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*UsePAM\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes
      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*UsePAM\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1
      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*UsePAM\s+
          line: UsePAM yes
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      tags:
      - CCE-86721-8


    - name: Ensure xinetd is removed
      package:
        name: xinetd
        state: absent


    - name: Ensure telnet-server is removed
      package:
        name: telnet-server
        state: absent
